import { PERMISSIONS, ROLE_KEYS, type Permission } from "@/modules/shared/permissions";

const PHASE3_GOVERNANCE_PERMISSIONS: Permission[] = [
  PERMISSIONS.GOVERNANCE_VIEW,
  PERMISSIONS.GOVERNANCE_SUBMIT,
  PERMISSIONS.APPROVAL_REVIEW,
  PERMISSIONS.DECISION_MAKE,
  PERMISSIONS.DECISION_CONDITION_RESOLVE,
  PERMISSIONS.POC_CREATE,
  PERMISSIONS.POC_EDIT,
  PERMISSIONS.POC_TRANSITION,
  PERMISSIONS.POC_EVALUATE,
  PERMISSIONS.APPROVAL_AUTHORITY_BUSINESS,
  PERMISSIONS.APPROVAL_AUTHORITY_ARCHITECTURE,
  PERMISSIONS.APPROVAL_AUTHORITY_SECURITY,
];

const PHASE4_PILOT_PROJECT_PERMISSIONS: Permission[] = [
  PERMISSIONS.PILOT_CREATE,
  PERMISSIONS.PILOT_EDIT,
  PERMISSIONS.PILOT_TRANSITION,
  PERMISSIONS.PILOT_EVALUATE,
  PERMISSIONS.PROJECT_CONVERT,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.PROJECT_EDIT,
  PERMISSIONS.PROJECT_CLOSE,
  PERMISSIONS.PROJECT_MANAGE_MILESTONES,
  PERMISSIONS.PROJECT_MANAGE_WORKITEMS,
  PERMISSIONS.GOVERNANCE_POLICY_MANAGE,
];

const PHASE5_PI_PLANNING_PERMISSIONS: Permission[] = [
  PERMISSIONS.PI_VIEW,
  PERMISSIONS.PI_CREATE,
  PERMISSIONS.PI_EDIT,
  PERMISSIONS.PI_TRANSITION,
  PERMISSIONS.PI_ALLOCATE,
  PERMISSIONS.PI_MANAGE_CAPACITY,
  PERMISSIONS.PI_MANAGE_DEPENDENCY,
  PERMISSIONS.PI_REVIEW,
  PERMISSIONS.PI_BASELINE,
];

const INITIATIVE_WRITE: Permission[] = [
  PERMISSIONS.INITIATIVE_VIEW,
  PERMISSIONS.INITIATIVE_CREATE,
  PERMISSIONS.INITIATIVE_EDIT,
  PERMISSIONS.INITIATIVE_MANAGE_DEMAND,
  PERMISSIONS.INITIATIVE_MANAGE_REQUIREMENTS,
  PERMISSIONS.INITIATIVE_MANAGE_PRESTUDY,
  PERMISSIONS.INITIATIVE_MANAGE_RISK,
  PERMISSIONS.INITIATIVE_ADVANCE,
];

/**
 * Platform Admin (bootstrap): platform administration only.
 * Business mutations require Organization Admin (granted on first org create)
 * or other scoped role packs — PLATFORM binding no longer wildcards them.
 */
export const PLATFORM_BOOTSTRAP_PERMISSIONS: Permission[] = [
  PERMISSIONS.PLATFORM_BOOTSTRAP,
  PERMISSIONS.ORG_STRUCTURE_READ,
  PERMISSIONS.ORG_STRUCTURE_MANAGE,
  PERMISSIONS.AUDIT_READ,
  PERMISSIONS.ROLE_MANAGE,
  PERMISSIONS.GOVERNANCE_POLICY_MANAGE,
];

/** Full organization administration within ORGANIZATION (or descendant) scope. */
export const ORGANIZATION_ADMIN_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORG_STRUCTURE_READ,
  PERMISSIONS.ORG_STRUCTURE_MANAGE,
  PERMISSIONS.AUDIT_READ,
  PERMISSIONS.ROLE_MANAGE,
  ...INITIATIVE_WRITE,
  ...PHASE3_GOVERNANCE_PERMISSIONS,
  ...PHASE4_PILOT_PROJECT_PERMISSIONS,
  ...PHASE5_PI_PLANNING_PERMISSIONS,
];

/** Portfolio: initiatives + projects + governance submit/view — not decisions/approvals/roles. */
export const PORTFOLIO_MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORG_STRUCTURE_READ,
  ...INITIATIVE_WRITE,
  PERMISSIONS.GOVERNANCE_VIEW,
  PERMISSIONS.GOVERNANCE_SUBMIT,
  PERMISSIONS.POC_CREATE,
  PERMISSIONS.POC_EDIT,
  PERMISSIONS.POC_TRANSITION,
  PERMISSIONS.POC_EVALUATE,
  PERMISSIONS.PILOT_CREATE,
  PERMISSIONS.PILOT_EDIT,
  PERMISSIONS.PILOT_TRANSITION,
  PERMISSIONS.PILOT_EVALUATE,
  PERMISSIONS.PROJECT_CONVERT,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.PROJECT_EDIT,
  PERMISSIONS.PROJECT_CLOSE,
  PERMISSIONS.PROJECT_MANAGE_MILESTONES,
  PERMISSIONS.PROJECT_MANAGE_WORKITEMS,
  PERMISSIONS.PI_VIEW,
];

/** Section manager: structure under section + portfolio delivery inside section. */
export const SECTION_MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORG_STRUCTURE_READ,
  PERMISSIONS.ORG_STRUCTURE_MANAGE,
  ...INITIATIVE_WRITE,
  PERMISSIONS.GOVERNANCE_VIEW,
  PERMISSIONS.GOVERNANCE_SUBMIT,
  PERMISSIONS.POC_CREATE,
  PERMISSIONS.POC_EDIT,
  PERMISSIONS.POC_TRANSITION,
  PERMISSIONS.POC_EVALUATE,
  PERMISSIONS.PILOT_CREATE,
  PERMISSIONS.PILOT_EDIT,
  PERMISSIONS.PILOT_TRANSITION,
  PERMISSIONS.PILOT_EVALUATE,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.PROJECT_EDIT,
  PERMISSIONS.PROJECT_CLOSE,
  PERMISSIONS.PROJECT_MANAGE_MILESTONES,
  PERMISSIONS.PROJECT_MANAGE_WORKITEMS,
  PERMISSIONS.PI_VIEW,
  PERMISSIONS.PI_CREATE,
  PERMISSIONS.PI_EDIT,
  PERMISSIONS.PI_TRANSITION,
  PERMISSIONS.PI_ALLOCATE,
  PERMISSIONS.PI_MANAGE_CAPACITY,
  PERMISSIONS.PI_MANAGE_DEPENDENCY,
  PERMISSIONS.PI_REVIEW,
];

/** Department manager: initiatives/projects in department; structure manage for teams. */
export const DEPARTMENT_MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORG_STRUCTURE_READ,
  PERMISSIONS.ORG_STRUCTURE_MANAGE,
  ...INITIATIVE_WRITE,
  PERMISSIONS.GOVERNANCE_VIEW,
  PERMISSIONS.GOVERNANCE_SUBMIT,
  PERMISSIONS.POC_CREATE,
  PERMISSIONS.POC_EDIT,
  PERMISSIONS.POC_TRANSITION,
  PERMISSIONS.POC_EVALUATE,
  PERMISSIONS.PILOT_CREATE,
  PERMISSIONS.PILOT_EDIT,
  PERMISSIONS.PILOT_TRANSITION,
  PERMISSIONS.PILOT_EVALUATE,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.PROJECT_EDIT,
  PERMISSIONS.PROJECT_CLOSE,
  PERMISSIONS.PROJECT_MANAGE_MILESTONES,
  PERMISSIONS.PROJECT_MANAGE_WORKITEMS,
  PERMISSIONS.PI_VIEW,
  PERMISSIONS.PI_ALLOCATE,
  PERMISSIONS.PI_MANAGE_CAPACITY,
  PERMISSIONS.PI_MANAGE_DEPENDENCY,
];

/** Team manager: team structure + capacity/allocation; no org/governance authority. */
export const TEAM_MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORG_STRUCTURE_READ,
  PERMISSIONS.ORG_STRUCTURE_MANAGE,
  PERMISSIONS.INITIATIVE_VIEW,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.PI_VIEW,
  PERMISSIONS.PI_ALLOCATE,
  PERMISSIONS.PI_MANAGE_CAPACITY,
];

/** Project manager: delivery execution inside project scope (granted at DEPARTMENT typically). */
export const PROJECT_MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORG_STRUCTURE_READ,
  PERMISSIONS.INITIATIVE_VIEW,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.PROJECT_EDIT,
  PERMISSIONS.PROJECT_CLOSE,
  PERMISSIONS.PROJECT_MANAGE_MILESTONES,
  PERMISSIONS.PROJECT_MANAGE_WORKITEMS,
  PERMISSIONS.PI_VIEW,
  PERMISSIONS.PI_ALLOCATE,
];

/** Read-only viewer. */
export const VIEWER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORG_STRUCTURE_READ,
  PERMISSIONS.INITIATIVE_VIEW,
  PERMISSIONS.GOVERNANCE_VIEW,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.PI_VIEW,
  PERMISSIONS.AUDIT_READ,
];

export type SystemRolePack = {
  key: string;
  name: string;
  description: string;
  permissions: Permission[];
};

export const SYSTEM_ROLE_PACKS: SystemRolePack[] = [
  {
    key: ROLE_KEYS.PLATFORM_BOOTSTRAP_ADMIN,
    name: "Platform Admin",
    description:
      "Platform bootstrap and security administration. Does not wildcard organization business mutations.",
    permissions: PLATFORM_BOOTSTRAP_PERMISSIONS,
  },
  {
    key: ROLE_KEYS.ORGANIZATION_ADMIN,
    name: "Organization Admin",
    description: "Full administration within an organization scope.",
    permissions: ORGANIZATION_ADMIN_PERMISSIONS,
  },
  {
    key: ROLE_KEYS.PORTFOLIO_MANAGER,
    name: "Portfolio Manager",
    description:
      "Initiative and project delivery management without approval/decision or role administration.",
    permissions: PORTFOLIO_MANAGER_PERMISSIONS,
  },
  {
    key: ROLE_KEYS.SECTION_MANAGER,
    name: "Section Manager",
    description: "Manage structure and delivery within a section and its descendants.",
    permissions: SECTION_MANAGER_PERMISSIONS,
  },
  {
    key: ROLE_KEYS.DEPARTMENT_MANAGER,
    name: "Department Manager",
    description: "Manage structure and delivery within a department and its teams.",
    permissions: DEPARTMENT_MANAGER_PERMISSIONS,
  },
  {
    key: ROLE_KEYS.TEAM_MANAGER,
    name: "Team Manager",
    description: "Manage team membership/capacity and view delivery artifacts.",
    permissions: TEAM_MANAGER_PERMISSIONS,
  },
  {
    key: ROLE_KEYS.PROJECT_MANAGER,
    name: "Project Manager",
    description: "Manage project work items and milestones within scope.",
    permissions: PROJECT_MANAGER_PERMISSIONS,
  },
  {
    key: ROLE_KEYS.VIEWER,
    name: "Viewer",
    description: "Read-only access within bound scope.",
    permissions: VIEWER_PERMISSIONS,
  },
];
